### ISSUE TITLE
Make dash a valid identifier

### ISSUE THREAD

**Issue by dmoskalik** [jmespath/jmespath.rb#12]
Why isn't dash ("-") a valid identifier? For example I cannot get the data when I specify a filter like `sc_host_name.my-pc`

My json:
```json
{ 
  "sc_host_name":{
    "my-pc":{
      "ip":"192.168.1.1"
    }
  }
}
```

I get an error
``` 
/usr/local/rvm/gems/ruby-2.2-head/gems/jmespath-1.1.3/lib/jmespath/parser.rb:41:in `parse': expected :eof got identifier (JMESPath::Errors::SyntaxError)
        from /usr/local/rvm/gems/ruby-2.2-head/gems/jmespath-1.1.3/lib/jmespath/caching_parser.rb:25:in `block in cache_expression'
        from /usr/local/rvm/gems/ruby-2.2-head/gems/jmespath-1.1.3/lib/jmespath/caching_parser.rb:23:in `synchronize'
        from /usr/local/rvm/gems/ruby-2.2-head/gems/jmespath-1.1.3/lib/jmespath/caching_parser.rb:23:in `cache_expression'
        from /usr/local/rvm/gems/ruby-2.2-head/gems/jmespath-1.1.3/lib/jmespath/caching_parser.rb:16:in `parse'
        from /usr/local/rvm/gems/ruby-2.2-head/gems/jmespath-1.1.3/lib/jmespath/runtime.rb:51:in `search'
        from /usr/local/rvm/gems/ruby-2.2-head/gems/jmespath-1.1.3/lib/jmespath.rb:33:in `search'
```

If I add - to the `VALID_IDENTIFIERS` in `lexer.rb` it works like a charm.

**Comment by trevorrowe** [comment]
Can you provide a sample expression to demonstrate the issue?  Here is what I attempted:

```ruby
require 'jmespath'

JMESPath.search("\"-\"", { "-" => true })
#=> true

JMESPath.search('"-"', { "-" => true })
#=> true
```

Please note, that according to the JMESPath grammar, the dash character needs to be expressed as a quoted identifier.

**Comment by mtdowling** [comment]
`-` is not valid in unquoted identifiers as it is used for negative numbers. We also might add support in the future for addition, subtraction, etc, which would preclude us from allowing dashes in unquoted identifiers. In order to work around this, you will need to quote the identifier e.g., `"foo-bar"`.

**Comment by dmoskalik** [comment]
Indeed if you quote it's ok

**Comment by trevorrowe** [comment]
Closing as a non issue as this is currently to the spec.
