### ISSUE TITLE
Add support for "and expressions" in filters.

### ISSUE THREAD

**Issue by elyobo** [jmespath/jmespath.rb#13]
The specification now includes ["and expressions"](http://jmespath.org/specification.html#and-expressions), but these are not yet supported in jmespath.rb.

```ruby
# JMESPath::Errors::SyntaxError: expected a closing rbracket for the filter
JMESPath.search('[?foo && bar]', {})
```

Edited: cleaned up to make this a feature request for "and expression" support.

**Comment by elyobo** [comment]
I checked out the behaviour of the PHP version on these as well and some of the same issues crop up.  Perhaps I'm misunderstanding some things?

* And expressions also fail with much the same error ("Expected a closing rbracket for the filter")
* Or expressions parse *and work as expected*
* Backticks *work as expected*, but single quotes are still allowed and double quotes parse but fail to match.

**Comment by elyobo** [comment]
WRT the strings, there seems to be some difference between the [original spec](https://jmespath.readthedocs.org/en/latest/proposals/filter-expressions.html#literal-expressions) and how this is defined in the [current spec](http://jmespath.org/specification.html#raw-string-literals).

On that basis, is seems like the ruby implementation is consistent with the current spec in accepting 'foo' and \`"foo"\`, and in rejecting \`foo\` (although I note that [the tutorial](http://jmespath.org/tutorial.html) does still permit \`foo\` style string delimiters).  The behaviour with double quoted strings, e.g. "foo", is odd though; shouldn't this be a parse error?

Overall this inconsistent behaviour between libraries is a bit of a hassle.

**Comment by trevorrowe** [comment]
This has been added in 526bcb6b3ec99f5add6b074e6e711ec733f6e4dc. Expect a new release shortly.

**Comment by elyobo** [comment]
Awesome, thanks @trevorrowe
