### ISSUE TITLE
Bad operator precedence and no support for parentheses

### ISSUE THREAD

**Issue by iconara** [jmespath/jmespath.rb#16]
```ruby
> JMESPath.search('n > `3` || `9999`', {n: 1})
 => false
```

This expression should have evaluated to `9999` (this is how Ruby, JavaScript and most other languages would interpret the expression, and it's also what you get on [jmespath.org](http://jmespath.org)), but it's interpreted as `n > (3 || 9999)`.

If parentheses had been supported there would have been a workaround, but I don't know if there is any other way to force the order of interpretation.

**Comment by trevorrowe** [comment]
Thanks for the bug report. The JMESPath specification does not implement parentheses, but I can bring this up for discussion.  I'll take at look at why the precedence is not as expected.

**Comment by trevorrowe** [comment]
@iconara So I miss-spoke. Apparently an update was made a few months back adding parenthesis to the expression language. I'll see about getting these added.

**Comment by iconara** [comment]
I would have submitted a PR, but I'm not at all at home with the parser unfortunately.

**Comment by trevorrowe** [comment]
I finally got around to updating to the latest spec. As of 526bcb6b3ec99f5add6b074e6e711ec733f6e4dc, this will now return the correct/expected value.
