### ISSUE TITLE
FYI: runtime dependency json 1.8.x

### ISSUE THREAD

**Issue by cdenneen** [jmespath/jmespath.rb#18]
This is just as FYI:

This gem since Sept when 1.1.3 was accidentally released without json runtime dependency has allowed systems shipped with json in ruby packages (Centos 7 with version 1.7.7) to work just fine for json dependent gems (like aws-sdk).
With the the 1.2.x release the dependency is back and systems that don't have ruby-devel (or equivalent on Windows) 

This inadvertently caused systems that didn't realize this dependency was necessary past 7 months in any sort of configuration management, autoscaling scenario, etc to fail because normal "gem install aws-sdk" now would fail because of the missing Ruby Devel dependency to build json with native extensions.

Note is systems built with things like Puppet Enterprise 201x.x.x are shipping with vendored ruby so if one is relying on installed aws-sdk within that using something like "pe_gem" most likely they wouldn't have a reason to have ruby installed on the system.

@puppetlabs @aws

**Comment by trevorrowe** [comment]
I am open to a discussion on possible work-arounds. I added the explicit dependency back because Ruby 1.9 ships with an older version of JSON. This version can not parse JSON scalar literal values:

```ruby
# in json 1.5.5 which ships with 1.9
JSON.parse('1') #=> raises an error

# in json 1.8.1+ which ships with 2.0+
JSON.parse('1') #=> 1
```

What if I replaced the hard dependency on `json >= 1.8.1` and replaced it with the `json_pure` gem? I could add a small amount of code to attempt to load the normal `json` gem, and follow-up with a load of json pure.

I'll put together a pull request as an example.

**Comment by sjones204g** [comment]
This is a blocking issue for my company. We're deploying Windows applications using Chef. Thank you for looking into it ASAP.

**Comment by trevorrowe** [comment]
I went ahead and merged the change and cut a 1.2.2 patch release.

**Comment by sjones204g** [comment]
Thank you!

**Comment by cdenneen** [comment]
@trevorrowe Thanks... my initial test seems to be good. I'll have my teams test their Windows and Linux builds that were failing but I think we are good with this fix. Thanks again!

**Comment by xeron** [comment]
This PR fixed runtime/gem load issue for us, but now we're getting another one when using `aws-sdk` and `json` inside `Chef`:
```
TypeError: wrong argument type JSON::Pure::Generator::State (expected Data)
```
