### ISSUE TITLE
drop json_pure dependency ?

### ISSUE THREAD

**Issue by grosser** [jmespath/jmespath.rb#22]
I already have enough json libraries ... and json works on rubinius/java/c ... so I'd love to not add yet another one to my project ... can this be a development dependency ?

@trevorrowe

**Comment by grosser** [comment]
looks like this is some kind of fix for a ruby 1.9.3 issue ... how about dropping 1.9.3 support ?
alternatively do a `JSON.load('1')` and if that fails instruct users how to update

**Comment by trevorrowe** [comment]
I would like to drop support for Ruby 1.9.3, but the primary downstream dependency (the `aws-sdk` gem) supports back through Ruby 1.9.3. The json_pure dependency is soft dependency. It will be forced to be present only as a fallback. This library will attempt first to load json/ext first.

**Comment by grosser** [comment]
then make it a soft/development dependency ... atm you force everyone to install it :(

adding something like this would make only 1.9.3 users have to deal with it ...
```
gem 'json_pure' if ruby1.9.3
```

**Comment by trevorrowe** [comment]
@grosser That approach has the negative side-effect of allowing 1.9.3 users to install jmespath and then have it fail at runtime, which would be a breaking change. I would consider this only with a major version bump of the library.

**Comment by grosser** [comment]
Then how about we do that ... maybe you want to get other breaking changes in too ... if not tag this issue v2.0 so it does not get lost ...

**Comment by trevorrowe** [comment]
That is a reasonable suggestion. I've created a label and milestone for a version 2.0. Currently there are no plans to version bump this library, but this will ensure this issue is not lost.

**Comment by fcarreiro** [comment]
+1 to dropping the `json_pure` dependency (or making it work better); it is also giving problems with Rails in #34.

**Comment by trevorrowe** [comment]
Closed by #35. We've removed the dependency on `json_pure`, and have added some additional code to deal with the old Ruby 1.9.3 & JSON 1.5.5 differences.
