### ISSUE TITLE
Tests Fail on 2.3.X

### ISSUE THREAD

**Issue by pmorton** [jmespath/jmespath.rb#30]
In doing some development on the gem I have found that there is one test that does not pass on ruby 2.3.X https://gist.github.com/pmorton/0a71895e3e98193533c302cdeccd74ac

The tests pass on 2.2 and jruby 1.7.

**Comment by trevorrowe** [comment]
Thanks for the report. I'll try to take a look at this shortly.

**Comment by trevorrowe** [comment]
Fixed by 33db62be005aa861e76d2c831adc4536d7f35d18. This should go out shortly with the next release.
