### ISSUE TITLE
JRuby implementation?

### ISSUE THREAD

**Issue by iconara** [jmespath/jmespath.rb#37]
We're working on a JRuby optimized JMESPath implementation based on [jmespath-java](https://github.com/burtcorp/jmespath-java). We've started it as a [separate thing](https://github.com/burtcorp/jmespath-jruby), but I wanted to know your opinion on building into `jmespath.rb` instead.

It would probably require some changes to the public API of `jmespath.rb`. We want to be able to cache expression objects, and the way that `jmespath.rb` works makes that unnecessarily hard and clumsy (and there's not even a public way to do it). You can see [an example of how we want the API to work here](https://github.com/burtcorp/jmespath-jruby), it's not a huge change, but it's a change.

If you're interested in us working on a combined `jmespath.rb` I can submit a PR with a proposal for how the public API would work, how the pure Ruby and the JRuby implementations could co-exist, and how it can be made to be somewhat backwards compatible.

If this is not of interest, that's ok, we will just release gems under the name `jmespath-jruby` and try to make it possible to have both `jmespath.rb` and `jmespath-jruby` installed at the same time (for example when you depend on a gem that already depends on `jmespath.rb`).

**Comment by trevorrowe** [comment]
I would be interested. Based on the external API example you linked, I don't see why the two interfaces could not co-exist.

**Comment by iconara** [comment]
Great. We forked jmespath.rb a while ago, but that fork has diverged too far to be salvaged (but we still depend on it), so I've asked GitHub for help so that we can create a new fork to start working in. Once that's done I'll open a PR with a proposal.

**Comment by iconara** [comment]
Let's continue this in #38.
