### ISSUE TITLE
jmespath search unexpected behavior when expression contains equality operators

### ISSUE THREAD

**Issue by DJStephan** [jmespath/jmespath.rb#59]
When using the #search method with equality operators there is some unexpected behavior. For example, if I have a hash:

```text
irb(main):092:1* hash = {
irb(main):093:2*   "top_level_key" => {
irb(main):094:2*     "inner_key" => "Hello World!"
irb(main):095:1*   }
irb(main):096:0> }
```
and an expression that does not match the hash:

```text
irb(main):102:0> expression = 'non_existent_key.inner_key'
=> "non_existent_key.inner_key"
```

I expect that if I call `JMESPath.search(expression, hash)` I should get `nil`, and that works as expected:

```text
irb(main):103:0> JMESPath.search(expression, hash)
=> nil
```

However, if I include an equality operator like:

```text
irb(main):104:0> expression = 'non_existent_key.inner_key == "Hello World!"'
=> "non_existent_key.inner_key == \"Hello World!\"
```

I would expect that `JMESPath.search` would return `false`, yet I get `true`:

```text
irb(main):106:1* hash = {
irb(main):107:2*   "top_level_key" => {
irb(main):108:2*     "inner_key" => "Hello World!"
irb(main):109:1*   }
irb(main):110:0> }
=> {"top_level_key"=>{"inner_key"=>"Hello World!"}}
irb(main):111:0> expression = 'non_existent_key.inner_key == "Hello World!"'
=> "non_existent_key.inner_key == \"Hello World!\""
irb(main):112:0> JMESPath.search(expression, hash)
=> true
```

**Comment by alextwoods** [comment]
I believe the[ literal expression](https://jmespath.org/specification.html#literal-expressions) in your search should use single quotes (`'`) instead of double (`"`).  Eg, the following correctly returns false for me:
```
expression = "non_existent_key.inner_key == 'Hello World!'" # use single quotes for the literal
JMESPath.search(expression, hash) # now returns false
```

The double quotes are used for escaping an identifier.  So in this case you are searching for a key `"Hello World"`, which in this hash will give you `null` and `null == null` is true, so that is being returned.

**Comment by DJStephan** [comment]
Ah, Thanks for the clarification!
