### ISSUE TITLE
Move to jmespath org?

### ISSUE THREAD

**Issue by mtdowling** [jmespath/jmespath.rb#8]
Since this project is post-1.0, does it make sense to move this repo to the jmespath org? It might make it more discoverable to be with the other official implementations.

@jamesls @trevorrowe

**Comment by trevorrowe** [comment]
Yes, it does. It looks like I am already in the jmespath org, so I'll see about making the transfer tonight.

**Comment by trevorrowe** [comment]
Done.

**Comment by mtdowling** [comment]
![image](https://cloud.githubusercontent.com/assets/190930/8123998/6f4eeb90-1088-11e5-9439-1fc1136b568a.png)

that was quick!
